apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registro-atividades
resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- api-deployment.yaml
- api-service.yaml
images:
- name: paulok3tchup/registro-k8s-2fort
  newTag: 56a5a5cc0c0bd69fb105b61a17d33c5ef8faeabd
